{
 "title": "ISS ETHOS",
 "description": "ISS ETHOS Telemetry",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "ISS Signal",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "target": "iss.time.time_.time_000001",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Cabin Temperature",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.uslab.uslab000059"
    }
   ]
  },
  {
   "title": "Lab Cooling Fluid Temp",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "alias(iss.telemetry.uslab.uslab000061, 'Air')"
    },
    {
     "target": "alias(iss.telemetry.uslab.uslab000060, 'Avionics')"
    }
   ]
  },
  {
   "title": "Urine Tank Quantity",
   "type": "graph",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.node3.node3000005"
    }
   ]
  },
  {
   "title": "Cabin Temperature",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "targets": [
    {
     "target": "iss.telemetry.uslab.uslab000059"
    }
   ]
  },
  {
   "title": "Cabin Pressure",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 2, "y": 3 },
   "yaxes": [
    { "format": "pressurepsi" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.uslab.uslab000058"
    }
   ]
  },
  {
   "title": "Waste Water Tank Quantity",
   "type": "graph",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.node3.node3000008"
    }
   ]
  },
  {
   "title": "Lab Coolant Water Quantity",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(iss.telemetry.uslab.uslab000056, 'LT')"
    },
    {
     "target": "alias(iss.telemetry.uslab.uslab000057, 'MT')"
    }
   ]
  },
  {
   "title": "Cabin Pressure",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "targets": [
    {
     "target": "iss.telemetry.uslab.uslab000058"
    }
   ]
  },
  {
   "title": "Crewlock Pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 2, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000049"
    }
   ]
  },
  {
   "title": "Clean Water Tank Quantity",
   "type": "graph",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.node3.node3000009"
    }
   ]
  },
  {
   "title": "Crewlock",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000049"
    }
   ]
  },
  {
   "title": "Node 2 Cooling Fluid Temp",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "alias(iss.telemetry.node2.node2000006, 'Air')"
    },
    {
     "target": "alias(iss.telemetry.node2.node2000007, 'Avionics')"
    }
   ]
  },
  {
   "title": "O2 Production rate",
   "type": "graph",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.node3.node3000011"
    }
   ]
  },
  {
   "title": "Hi P O2",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000055"
    }
   ]
  },
  {
   "title": "Airlock Pressure",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 2, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000054"
    }
   ]
  },
  {
   "title": "Node 3 Cooling Fluid Temp",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "alias(iss.telemetry.node3.node3000013, 'Air')"
    },
    {
     "target": "alias(iss.telemetry.node3.node3000012, 'Avionics')"
    }
   ]
  },
  {
   "title": "Lab Air Parts Per",
   "type": "graph",
   "description": "Shows O2, N2 & CO2 amounts in parts per.\nUnits is actually PSIA (Pounds Square Inch Absolute)",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(iss.telemetry.uslab.uslab000053, 'O2')"
    },
    {
     "target": "alias(iss.telemetry.uslab.uslab000054, 'N2')"
    },
    {
     "target": "alias(iss.telemetry.uslab.uslab000055, 'CO2')"
    }
   ]
  },
  {
   "title": "Lo P O2",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000056"
    }
   ]
  },
  {
   "title": "Airlock O2 Tank Pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 2, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(iss.telemetry.airlock.airlock000055, 'Hi P')"
    },
    {
     "target": "alias(iss.telemetry.airlock.airlock000056, 'Lo P')"
    }
   ]
  },
  {
   "title": "Node 2 Coolant water quantity",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(iss.telemetry.node2.node2000001, 'Node 2 MT')"
    },
    {
     "target": "alias(iss.telemetry.node2.node2000002, 'Node 2 LT')"
    },
    {
     "target": "alias(iss.telemetry.node3.node3000019, 'Node 3')"
    }
   ]
  },
  {
   "title": "N2",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000057"
    }
   ]
  },
  {
   "title": "Airlock N2 Tank Pressure",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 2, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000057"
    }
   ]
  }
 ]
}