{
 "title": "ISS EVA",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "ISS Signal",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "target": "iss.time.time_.time_000001",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "BCA1 Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000019"
    }
   ]
  },
  {
   "title": "BCA2 Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000020"
    }
   ]
  },
  {
   "title": "BCA3 Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000021"
    }
   ]
  },
  {
   "title": "BCA4 Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000022"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000023"
    }
   ]
  },
  {
   "title": "EMU1 Voltage through UIA",
   "type": "graph",
   "description": "Supplies power through the Umbilical Interface Assembly (UIA) to the spacesuits (EMU 1), Voltage",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000001"
    }
   ]
  },
  {
   "title": "EMU1 Current through UIA",
   "type": "graph",
   "description": "Supplies power through the Umbilical Interface Assembly (UIA) to the spacesuits (EMU 1), Current",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000002"
    }
   ]
  },
  {
   "title": "EMU2 Voltage through UIA",
   "type": "graph",
   "description": "Supplies power through the Umbilical Interface Assembly (UIA) to the spacesuits (EMU 2), Voltage",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000003"
    }
   ]
  },
  {
   "title": "EMU2 Current through UIA",
   "type": "graph",
   "description": "Supplies power through the Umbilical Interface Assembly (UIA) to the spacesuits (EMU 2), Current",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000004"
    }
   ]
  },
  {
   "title": "EMU1 Voltage power to spacesuit",
   "type": "graph",
   "description": "Supplies power to the spacesuits (EVA Mobility Unit, EMU 1), Voltage",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000007"
    }
   ]
  },
  {
   "title": "EMU1 Current power to spacesuit",
   "type": "graph",
   "description": "Supplies power to the spacesuits (EVA Mobility Unit, EMU 1), Current",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000008"
    }
   ]
  },
  {
   "title": "EMU2 Voltage power to spacesuit",
   "type": "graph",
   "description": "Supplies power to the spacesuits (EVA Mobility Unit, EMU 2), Voltage",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000009"
    }
   ]
  },
  {
   "title": "EMU2 Current power to spacesuit",
   "type": "graph",
   "description": "Supplies power to the spacesuits (EVA Mobility Unit, EMU 2), Current",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000010"
    }
   ]
  },
  {
   "title": "In-flight Refill Unit (IRU), Voltage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000005"
    }
   ]
  },
  {
   "title": "In-flight Refill Unit (IRU), Current",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000006"
    }
   ]
  },
  {
   "title": "Battery Charger Assemblies 1, 2, 3 & 4 Voltage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000011"
    },
    {
     "target": "iss.telemetry.airlock.airlock000013"
    },
    {
     "target": "iss.telemetry.airlock.airlock000015"
    },
    {
     "target": "iss.telemetry.airlock.airlock000017"
    }
   ]
  },
  {
   "title": "Battery Charger Assemblies 1, 2, 3 & 4 Current",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "iss.telemetry.airlock.airlock000012"
    },
    {
     "target": "iss.telemetry.airlock.airlock000014"
    },
    {
     "target": "iss.telemetry.airlock.airlock000016"
    },
    {
     "target": "iss.telemetry.airlock.airlock000018"
    }
   ]
  }
 ]
}