{
 "title": "ISS SPARTAN Power Console",
 "description": "ISS ETHOS Telemetry",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "content": "<div style=\"background:#008822\"><span style=\"font-size:300%;\">SPARTAN</span>Power Console Display</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "content": "<div style=\"font-size:150%;text-align:center;\">Station Power, Articulation & Thermal Control</div>"
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "target": "iss.telemetry.p6.p6000004" },
    { "target": "iss.telemetry.p4.p4000004" },
    { "target": "iss.telemetry.p6.p6000001" },
    { "target": "iss.telemetry.p4.p4000001" },
    { "target": "iss.telemetry.s4.s4000001" },
    { "target": "iss.telemetry.s6.s6000001" },
    { "target": "iss.telemetry.s4.s4000004" },
    { "target": "iss.telemetry.s6.s6000004" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 0, "y": 3 },
   "content": "<div style=\"background:#0000ff;height:16em;text-align:center;\">Ch<br/>2B</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 1, "y": 3 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.p6.p6000004" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 2, "y": 3 },
   "content": "<div style=\"background:#0000ff;height:16em;text-align:center;\">Ch<br/>4A</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 3 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.p4.p4000004" }
   ]
  },
  {
   "title": "Port",
   "type": "singlestat",
   "description": "Solar Alpha Rotary Joint Positions (degrees) for the Port side of the station",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 3 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.s0.s0000004" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 6, "y": 3 },
   "content": "<div style=\"background:#0000ff;height:16em;text-align:center;\">Ch<br/>1A</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 7, "y": 3 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.s4.s4000001" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 8, "y": 3 },
   "content": "<div style=\"background:#0000ff;height:16em;text-align:center;\">Ch<br/>3B</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 3 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.s6.s6000001" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 1, "y": 5 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.p6.p6000005" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 5 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.p4.p4000005" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 7, "y": 5 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.s4.s4000002" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 5 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.s6.s6000002" }
   ]
  },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "target": "iss.telemetry.p6.p6000005" },
    { "target": "iss.telemetry.p4.p4000005" },
    { "target": "iss.telemetry.p6.p6000002" },
    { "target": "iss.telemetry.p4.p4000002" },
    { "target": "iss.telemetry.s4.s4000002" },
    { "target": "iss.telemetry.s6.s6000002" },
    { "target": "iss.telemetry.s4.s4000005" },
    { "target": "iss.telemetry.s6.s6000005" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 1, "y": 7 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.p6.p6000008" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 7 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.p4.p4000008" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 7, "y": 7 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.s4.s4000007" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 7 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.s6.s6000007" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "content": "<div style=\"background:#666666;height:2em;border: 1px solid #eeeeee\">Port 6</div>\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
   "content": "<div style=\"background:#666666;height:2em;border: 1px solid #eeeeee\">Port 4</div>\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 9 },
   "content": "<div style=\"background:#666666;height:2em;border: 1px solid #eeeeee\">Crew modules</div>\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 9 },
   "content": "<div style=\"background:#666666;height:2em;border: 1px solid #eeeeee\">Stbd 4</div>\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 9 },
   "content": "<div style=\"background:#666666;height:2em;border: 1px solid #eeeeee\">Stbd 6</div>\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 0, "y": 11 },
   "content": "<div style=\"background:#0000ff;height:16em;text-align:center;\">Ch<br/>4B</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 1, "y": 11 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.p6.p6000001" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 2, "y": 11 },
   "content": "<div style=\"background:#0000ff;height:16em;text-align:center;\">Ch<br/>2A</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 11 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.p4.p4000001" }
   ]
  },
  {
   "title": "Starboard",
   "type": "singlestat",
   "description": "Solar Alpha Rotary Joint Positions (degrees) for the Starboard side of the station",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 11 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.s0.s0000003" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 6, "y": 11 },
   "content": "<div style=\"background:#0000ff;height:16em;text-align:center;\">Ch<br/>3A</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 7, "y": 11 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.s4.s4000004" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 8, "y": 11 },
   "content": "<div style=\"background:#0000ff;height:16em;text-align:center;\">Ch<br/>1B</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 11 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.s6.s6000004" }
   ]
  },
  {
   "title": "Array Position",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    { "target": "iss.telemetry.p6.p6000008" },
    { "target": "iss.telemetry.p4.p4000008" },
    { "target": "iss.telemetry.p6.p6000007" },
    { "target": "iss.telemetry.p4.p4000007" },
    { "target": "iss.telemetry.s4.s4000007" },
    { "target": "iss.telemetry.s6.s6000007" },
    { "target": "iss.telemetry.s4.s4000008" },
    { "target": "iss.telemetry.s6.s6000008" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 1, "y": 13 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.p6.p6000002" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 13 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.p4.p4000002" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 7, "y": 13 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.s4.s4000005" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 13 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.s6.s6000005" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 1, "y": 15 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.p6.p6000007" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 15 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.p4.p4000007" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 7, "y": 15 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.s4.s4000008" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 15 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    { "target": "iss.telemetry.s6.s6000008" }
   ]
  }
 ]
}